apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-machine-deployment
spec:
  replicas: 3                          # Number of pod replicas
  selector:
    matchLabels:
      app: user-machine
  template:
    metadata:
      labels:
        app: user-machine
    spec:
      containers:
      - name: user-machine-container
        image: ryanjule/user-machine:latest             # Docker image for your app
        env:
        - name: SMTP_EMAIL
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: SMTP_EMAIL
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: SMTP_PASSWORD
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET_KEY
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 8080           # Port for your app
        resources:
          requests:
            memory: "512Mi"             # Minimum memory requested
            cpu: "500m"                 # Minimum CPU requested (0.5 vCPU)
          limits:
            memory: "1Gi"               # Maximum memory allowed
            cpu: "1000m"