apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usermachine-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust storage size based on your needs
