apiVersion: v1
kind: Service
metadata:
  name: user-machine-service
spec:
  type: NodePort                       # Use LoadBalancer for cloud environments
  selector:
    app: user-machine
  ports:
  - protocol: TCP
    port: 8080                         # Kubernetes service port
    targetPort: 8080                   # Port of the app inside the pod
    nodePort: 30001                    # External port for access
